tenant: tyvdh
app: stellarauth
service: stellarauth-postgresql

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpsProtocol: certs
    port: 5000

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml)}

functions:
  users:
    handler: handler.users
    events:
      - http:
          method: ANY
          path: users
          cors: true
