service: stellarauth-postgresql

plugins:
  - serverless-webpack
  - serverless-offline
  # - serverless-domain-manager

custom:
  # customDomain:
  #   domainName: api.stellarauth.com
  #   certificateName: api.stellarauth.com
  #   stage: dev
  #   createRoute53Record: false
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    httpsProtocol: certs
    port: 5000

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment: ${file(env.yml):${self:provider.stage}}

functions:
  users:
    handler: handler.users
    events:
      - http:
          method: ANY
          path: users
          cors: true
